### ISSUE TITLE
Stopped working today

### ISSUE THREAD

**Issue by mrx23dot** [alexandreseris/youtube_silent_ad#1]
Ads are not muted :(
Worked great so far!

Version
1.0

**Comment by alexandreseris** [comment]
Hi,
I noticed too, I will take a look !

**Comment by alexandreseris** [comment]
well youtube is too smart for me
when i use devtools, the add disapear after a few seconds, therefore i can't analyze the dom to target the add :(

since i can't do anything, i'm closing this and the project, sorry!

**Comment by alexandreseris** [comment]
ok so i found something finnaly :)
and i upgraded the code so it mute immediately the ad instead of having a 500ms delay!
